version: "2"

networks:
  historiaclinicabasic:
services:
  # eps1
  root.ca.eps1.historiaclinicaelectronica.com:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: root.ca.eps1.historiaclinicaelectronica.com
    ports:
      - "7054:7054"
    volumes:
      - ./fabric-ca/eps1.historiaclinicaelectronica.com/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - historiaclinicabasic
  tls.root.ca.eps1.historiaclinicaelectronica.com:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.root.ca.eps1.historiaclinicaelectronica.com
    ports:
      - "7055:7054"
    volumes:
      - ./fabric-ca/eps1.historiaclinicaelectronica.com/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - historiaclinicabasic
  # eps2
  root.ca.eps2.historiaclinicaelectronica.com:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: root.ca.eps2.historiaclinicaelectronica.com
    ports:
      - "8054:7054"
    volumes:
      - ./fabric-ca/eps2.historiaclinicaelectronica.com/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - historiaclinicabasic
  tls.root.ca.eps2.historiaclinicaelectronica.com:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.root.ca.eps2.historiaclinicaelectronica.com
    ports:
      - "8055:7054"
    volumes:
      - ./fabric-ca/eps2.historiaclinicaelectronica.com/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - historiaclinicabasic
  # eps3
  root.ca.eps3.historiaclinicaelectronica.com:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: root.ca.eps3.historiaclinicaelectronica.com
    ports:
      - "9054:7054"
    volumes:
      - ./fabric-ca/eps3.historiaclinicaelectronica.com/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - historiaclinicabasic
  tls.root.ca.eps3.historiaclinicaelectronica.com:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.root.ca.eps3.historiaclinicaelectronica.com
    ports:
      - "9055:7054"
    volumes:
      - ./fabric-ca/eps3.historiaclinicaelectronica.com/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - historiaclinicabasic
