version: "2"

services:

  orderer.eps1.historiaclinicaelectronica.com:
    container_name: orderer.eps1.historiaclinicaelectronica.com
    extends:
      file: orderer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Eps1MSP
    volumes:
      # - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      # - ../crypto-config/ordererOrganizations/historiaclinicaelectronica.com/orderers/orderer.historiaclinicaelectronica.com/msp:/var/hyperledger/orderer/msp
      # - ../crypto-config/ordererOrganizations/historiaclinicaelectronica.com/orderers/orderer.historiaclinicaelectronica.com/tls/:/var/hyperledger/orderer/tls
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../fabric-ca/eps1.historiaclinicaelectronica.com/orderers/orderer.eps1.historiaclinicaelectronica.com/msp:/var/hyperledger/orderer/msp
      - ../fabric-ca/eps1.historiaclinicaelectronica.com/orderers/orderer.eps1.historiaclinicaelectronica.com/tls/:/var/hyperledger/orderer/tls
      - ../fabric-ca/eps1.historiaclinicaelectronica.com/orderers/orderer.eps1.historiaclinicaelectronica.com/production:/var/hyperledger/production/orderer

    ports:
      - 7050:7050
  
  orderer.eps2.historiaclinicaelectronica.com:
    container_name: orderer.eps2.historiaclinicaelectronica.com
    extends:
      file: orderer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Eps2MSP
    volumes:
      # - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      # - ../crypto-config/ordererOrganizations/historiaclinicaelectronica.com/orderers/orderer2.historiaclinicaelectronica.com/msp:/var/hyperledger/orderer/msp
      # - ../crypto-config/ordererOrganizations/historiaclinicaelectronica.com/orderers/orderer2.historiaclinicaelectronica.com/tls/:/var/hyperledger/orderer/tls
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../fabric-ca/eps2.historiaclinicaelectronica.com/orderers/orderer.eps2.historiaclinicaelectronica.com/msp:/var/hyperledger/orderer/msp
      - ../fabric-ca/eps2.historiaclinicaelectronica.com/orderers/orderer.eps2.historiaclinicaelectronica.com/tls/:/var/hyperledger/orderer/tls
      - ../fabric-ca/eps2.historiaclinicaelectronica.com/orderers/orderer.eps2.historiaclinicaelectronica.com/production:/var/hyperledger/production/orderer
    ports:
      - 8050:7050

  orderer.eps3.historiaclinicaelectronica.com:
    container_name: orderer.eps3.historiaclinicaelectronica.com
    extends:
      file: orderer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Eps3MSP
    volumes:
      # - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      # - ../crypto-config/ordererOrganizations/historiaclinicaelectronica.com/orderers/orderer3.historiaclinicaelectronica.com/msp:/var/hyperledger/orderer/msp
      # - ../crypto-config/ordererOrganizations/historiaclinicaelectronica.com/orderers/orderer3.historiaclinicaelectronica.com/tls/:/var/hyperledger/orderer/tls
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../fabric-ca/eps3.historiaclinicaelectronica.com/orderers/orderer.eps3.historiaclinicaelectronica.com/msp:/var/hyperledger/orderer/msp
      - ../fabric-ca/eps3.historiaclinicaelectronica.com/orderers/orderer.eps3.historiaclinicaelectronica.com/tls/:/var/hyperledger/orderer/tls
      - ../fabric-ca/eps3.historiaclinicaelectronica.com/orderers/orderer.eps3.historiaclinicaelectronica.com/production:/var/hyperledger/production/orderer
    ports:
      - 9050:7050

  # ---CHANGED--- The peer name is taken from the name generated by the "cryptogen" certs – it indicates the peer org 1 and one peer "peer0"
  peer0.eps1.historiaclinicaelectronica.com:
    # ---CHANGED--- Container name – same as the peer name
    container_name: peer0.eps1.historiaclinicaelectronica.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_ID=peer0.eps1.historiaclinicaelectronica.com
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_ADDRESS=peer0.eps1.historiaclinicaelectronica.com:7051
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.eps1.historiaclinicaelectronica.com:7051
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.eps1.historiaclinicaelectronica.com:7051      
      - CORE_PEER_LOCALMSPID=Eps1MSP
    volumes:
        - /var/run/:/host/var/run/
        # # ---CHANGED--- changed to reflect peer name, org name and our company's domain
        # - ../crypto-config/peerOrganizations/eps1.historiaclinicaelectronica.com/peers/peer0.eps1.historiaclinicaelectronica.com/msp:/etc/hyperledger/fabric/msp
        # # ---CHANGED--- changed to reflect peer name, org name and our company's domain
        # - ../crypto-config/peerOrganizations/eps1.historiaclinicaelectronica.com/peers/peer0.eps1.historiaclinicaelectronica.com/tls:/etc/hyperledger/fabric/tls
        - ../fabric-ca/eps1.historiaclinicaelectronica.com/peers/peer0.eps1.historiaclinicaelectronica.com/msp:/etc/hyperledger/fabric/msp
        - ../fabric-ca/eps1.historiaclinicaelectronica.com/peers/peer0.eps1.historiaclinicaelectronica.com/tls:/etc/hyperledger/fabric/tls
        - ../fabric-ca/eps1.historiaclinicaelectronica.com/peers/peer0.eps1.historiaclinicaelectronica.com/production:/var/hyperledger/production

    ports:
      - 7051:7051

  # ---CHANGED--- The peer name is taken from the name generated by the "cryptogen" certs – it indicates the peer org 2 and one peer "peer0"
  peer0.eps2.historiaclinicaelectronica.com:
    # ---CHANGED--- Container name – same as the peer name
    container_name: peer0.eps2.historiaclinicaelectronica.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_ID=peer0.eps2.historiaclinicaelectronica.com
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_ADDRESS=peer0.eps2.historiaclinicaelectronica.com:7051
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.eps2.historiaclinicaelectronica.com:7051
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.eps2.historiaclinicaelectronica.com:7051
      # ---CHANGED--- ensure that the MSP ID is correctly set of Eps2
      - CORE_PEER_LOCALMSPID=Eps2MSP
    volumes:
        - /var/run/:/host/var/run/
        # # ---CHANGED--- changed to reflect peer name, org name and our company's domain
        # - ../crypto-config/peerOrganizations/eps2.historiaclinicaelectronica.com/peers/peer0.eps2.historiaclinicaelectronica.com/msp:/etc/hyperledger/fabric/msp
        # # ---CHANGED--- changed to reflect peer name, org name and our company's domain
        # - ../crypto-config/peerOrganizations/eps2.historiaclinicaelectronica.com/peers/peer0.eps2.historiaclinicaelectronica.com/tls:/etc/hyperledger/fabric/tls
        - ../fabric-ca/eps2.historiaclinicaelectronica.com/peers/peer0.eps2.historiaclinicaelectronica.com/msp:/etc/hyperledger/fabric/msp
        - ../fabric-ca/eps2.historiaclinicaelectronica.com/peers/peer0.eps2.historiaclinicaelectronica.com/tls:/etc/hyperledger/fabric/tls
        - ../fabric-ca/eps2.historiaclinicaelectronica.com/peers/peer0.eps2.historiaclinicaelectronica.com/production:/var/hyperledger/production

    ports:
      - 8051:7051

  # ---CHANGED--- The peer name is taken from the name generated by the "cryptogen" certs – it indicates the peer org 3 and one peer "peer0"
  peer0.eps3.historiaclinicaelectronica.com:
    # ---CHANGED--- Container name – same as the peer name
    container_name: peer0.eps3.historiaclinicaelectronica.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_ID=peer0.eps3.historiaclinicaelectronica.com
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_ADDRESS=peer0.eps3.historiaclinicaelectronica.com:7051
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.eps3.historiaclinicaelectronica.com:7051
      # ---CHANGED--- changed to reflect peer name, org name and our company's domain
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.eps3.historiaclinicaelectronica.com:7051
      # ---CHANGED--- ensure that the MSP ID is correctly set of Org3
      - CORE_PEER_LOCALMSPID=Eps3MSP
    volumes:
        - /var/run/:/host/var/run/
        # # ---CHANGED--- changed to reflect peer name, org name and our company's domain
        # - ../crypto-config/peerOrganizations/eps3.historiaclinicaelectronica.com/peers/peer0.eps3.historiaclinicaelectronica.com/msp:/etc/hyperledger/fabric/msp
        # # ---CHANGED--- changed to reflect peer name, org name and our company's domain
        # - ../crypto-config/peerOrganizations/eps3.historiaclinicaelectronica.com/peers/peer0.eps3.historiaclinicaelectronica.com/tls:/etc/hyperledger/fabric/tls
        - ../fabric-ca/eps3.historiaclinicaelectronica.com/peers/peer0.eps3.historiaclinicaelectronica.com/msp:/etc/hyperledger/fabric/msp
        - ../fabric-ca/eps3.historiaclinicaelectronica.com/peers/peer0.eps3.historiaclinicaelectronica.com/tls:/etc/hyperledger/fabric/tls
        - ../fabric-ca/eps3.historiaclinicaelectronica.com/peers/peer0.eps3.historiaclinicaelectronica.com/production:/var/hyperledger/production
    ports:
      - 9051:7051